#deployment:
#  production:
#    branch: master
#    commands:
#      - ./deploy_prod.sh

#test:
#  override:
#    - echo 'no tests, just say us Okay!'

version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: /deploy_prod.sh
  test:
    machine:
      enabled: true  
    steps:
      - checkout
      - echo 'no tests, just say us Okay!'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
