#deployment:
#  production:
#    branch: master
#    commands:
#      - ./deploy_prod.sh

#test:
#  override:
#    - echo 'no tests, just say us Okay!'

version: 2
jobs:
  build:
    machine: true
    steps:
#      - checkout
#      - run: ./deploy_prod.sh
      - run: echo "hello world!"
