#deployment:
#  production:
#    branch: master
#    commands:
#      - ./deploy_prod.sh

version: 2
jobs:
   build:
     docker:
       - image: circleci/node:stretch
     steps:
       - checkout
       - command: ssh -vv -o "StrictHostKeyChecking=no" root@35.205.152.169 
