#deployment:
#  production:
#    branch: master
#    commands:
#      - ./deploy_prod.sh

version: 2
jobs:
   build:
     docker:
       - image: circleci/node:stretch
     steps:
       - checkout
       - run: ls #./deploy_prod.sh
